### ISSUE TITLE
Logging level

### ISSUE THREAD

**Issue by tomer953** [peatiscoding/wowza-webrtc-client#2]
Hi,

thanks for this package !

working with many streams, the  console got a lot of printing, and then It getting hard to filter other important messages.

if you can add some flag to disable all the player console.log() outputs, it would be nice 

thank you!

**Comment by peatiscoding** [comment]
I've updated the npm package v0.0.21. Please try it out.

They way I did it is; if you wish to see debug message. Simple access your browser console. And set 

```
window.cnsl_debug = true
```

it should print out all the messages. Otherwise it will should stay dead silent :)
